name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      # 1. Get the code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # 3. Install Python dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 4. Check Python code
      - name: Validate Python
        run: |
          python -m compileall backend

      # 5. Create environment file
      - name: Create .env
        run: |
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> backend/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> backend/.env

      # 6. Build Docker containers
      - name: Build Docker
        run: |
          docker compose build

      # 7. Start application
      - name: Start Docker
        run: |
          docker compose up -d

      # 8. Check containers
      - name: Check Docker
        run: |
          docker compose ps

      # 9. Stop containers
      - name: Stop Docker
        if: always()
        run: |
          docker compose down